[package]
name = "sg_samplesheet_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
bio = "1.3.1"
csv = "1.2.2"
